module.exports={
    html:{
        "Content-Type":"text/html"
    },
    text:{
        "Content-Type":"text/plain"
    },
    js:{
        "Content-Type":"text/js"
    },
    jpg:{
        "Content-Type":"image/jpg"
    },
    png:{
        "Content-Type":"image/png"
    },
    gif:{
        "Content-Type":"image/gif"
    },
    css:{
        "Content-Type":"text/css"
    },
    jpeg:{
        "Content-Type":"image/jpeg"
    },
}